/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f0e1c27d-dce8-479c-9f1d-ab248e445609",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_joMCngqnn",
    "aws_user_pools_web_client_id": "7931g47uvbe6h4rln2a1nnmp7j",
    "oauth": {}
};


export default awsmobile;
